tab=read.csv2("Cocchella_Ludovica_Tabella.csv", row.names = 1) 
str(tab)
head(tab)
round(cor(tab),2)
tab.pca=princomp(tab) 
biplot(tab.pca,cex=0.3)
tab.st.pca = princomp(scale(tab))
biplot(tab.st.pca, cex=0.6)
summary(tab.st.pca) 
plot(tab.st.pca)
plot(cumsum(tab.st.pca$sdev^2)/sum(tab.st.pca$sdev^2),type="b",ylim=c(0,1))
loadings(tab.st.pca)
biplot(tab.st.pca, choices = c(1,3), cex=0.6)
tab.st.ld=loadings(tab.st.pca)
varimax(tab.st.ld[,1:3])
ranking=round(predict(tab.st.pca)[,1],2)
sort(ranking)
